name: Run code linter "black"

on:
  push:
    branches: [ develop, build ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt install python3-pip python3-setuptools -y
    - run: pip3 install black
    - run: python3 -m black --check .
