name: Build executables for Linux Legacy
on:
  push:
    branches: [ main, develop, build ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Insatll requirements
      run: |
        python -m pip install --upgrade pip setuptools --ignore-installed
        python -m pip install --upgrade wheel pyinstaller
        python -m pip install -r requirements.txt

    - name: Build single executable
      run: pyinstaller pyfiledrop.py --onefile

    - name: Test executable
      run: dist/pyfiledrop --help

    - name: Upload standalone executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: pyfiledrop_linux_x86_64
        path: |
          dist/pyfiledrop
