name: Build executables for Windows
on:
  push:
    branches: [ main, develop, build ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Insatll requirements
      shell: cmd
      run: |
        python -m pip install --upgrade pip setuptools --ignore-installed
        python -m pip install --upgrade pypiwin32 wheel pyinstaller
        python -m pip install -r requirements.txt

    - name: Build single executable
      shell: cmd
      run: pyinstaller pyfiledrop.py --onefile

    - name: Test executable
      run: dist\pyfiledrop.exe --help

    - name: Upload standalone executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: pyfiledrop_win64
        path: dist\pyfiledrop.exe
